# Generated by Django 2.1.3 on 2018-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name your desired gift', max_length=200)),
                ('description', models.TextField(help_text='Describe your desired gift', max_length=2000)),
                ('link', models.URLField()),
                ('price', models.IntegerField()),
                ('desirability_rank', models.IntegerField()),
                ('date_saved', models.DateTimeField()),
                ('filled', models.BooleanField()),
            ],
        ),
    ]
