# Generated by Django 2.1.3 on 2018-11-14 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0003_auto_20181114_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='desirability_rank',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
