# Generated by Django 2.1.3 on 2018-11-15 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftsharingapp', '0005_auto_20181114_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='gift',
            name='active_til',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='filled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gift',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
