# Generated by Django 2.1.3 on 2018-11-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0008_auto_20181115_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
