# Generated by Django 2.1.3 on 2018-11-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0009_auto_20181116_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gifter_groups',
            field=models.ManyToManyField(related_name='members', to='giftsharingapp.GifterGroup'),
        ),
    ]
