# Generated by Django 2.1.3 on 2018-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0011_auto_20181116_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='active_til',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
