# Generated by Django 2.1.3 on 2018-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0012_auto_20181116_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['owner']},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
