# Generated by Django 2.1.3 on 2018-12-07 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0014_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
