# Generated by Django 2.1.3 on 2019-10-15 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftsharingapp', '0016_friendinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_colors', models.TextField(blank=True, max_length=2000, null=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True)),
                ('is_common_holiday', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='friendinvite',
            old_name='date_invited',
            new_name='date_sent',
        ),
        migrations.RenameField(
            model_name='friendinvite',
            old_name='friend_email',
            new_name='email_to',
        ),
        migrations.RemoveField(
            model_name='friendinvite',
            name='inviter',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friendinvite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftsharingapp.FriendInvite'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='shared_with_groups',
            field=models.ManyToManyField(to='giftsharingapp.GifterGroup'),
        ),
        migrations.AddField(
            model_name='gift',
            name='shared_with_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftergroup',
            name='group_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftergroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='date_accepted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendinvite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendinvite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='friendinvite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='giftsharingapp.FriendInvite'),
        ),
        migrations.AddField(
            model_name='gift',
            name='occasion',
            field=models.ManyToManyField(to='giftsharingapp.Occasion'),
        ),
    ]
