# Generated by Django 2.1.3 on 2019-10-17 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftsharingapp', '0019_auto_20191015_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=10000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('friendship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftsharingapp.Friendship')),
            ],
        ),
        migrations.CreateModel(
            name='GiftQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=2000, null=True)),
                ('answer', models.TextField(blank=True, max_length=2000, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='giftsharingapp.Gift')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_added_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftUpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftupdate_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftupdate_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='friendinvite',
            old_name='sent_by',
            new_name='sent_by_user',
        ),
        migrations.RenameField(
            model_name='friendinvite',
            old_name='sent_to',
            new_name='sent_to_user',
        ),
        migrations.AddField(
            model_name='friendinvite',
            name='token',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='issuer_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='issuer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='friendinvite',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
