# Generated by Django 2.1.3 on 2019-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0024_auto_20191017_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='user',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='giftergroup',
            name='group_admins',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
