# Generated by Django 2.1.3 on 2019-10-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0025_auto_20191018_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='limited_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
