# Generated by Django 2.1.3 on 2019-10-20 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0026_gift_limited_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_suggested_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gift',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_added_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
