# Generated by Django 2.1.3 on 2019-10-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsharingapp', '0027_auto_20191020_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftergroup',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
